name: Sync File to S3

on:
  push:
    branches:
      - develop # Solo se ejecutará cuando haya cambios en la rama main
      - qa
      - prod

permissions:
  id-token: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    enviroment:
      - name: $ {{ref.branch}}
    env:
      AWS_BUCKET_NAME: "prueba-exampe-josemaria-git"
      REGION: "us-east-1"
      JUANPI: ${{ vars.JUANPI }}
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Parametros
        run: |
          echo "$REGION"
      
      - name: Set Parameters File
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            echo "PARAMETERS_FILE=./parameters-dev.json" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "qa" ]]; then
            echo "PARAMETERS_FILE=./parameters-qa.json" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "prod" ]]; then
            echo "PARAMETERS_FILE=./parameters-prod.json" >> $GITHUB_ENV
          else
            echo "No es la rama correcta" >> $GITHUB_ENV
          fi

      - name: Load JSON into Environment Variables
        run: |
          for row in $(jq -c '.[]' $PARAMETERS_FILE); do
            key=$(echo $row | jq -r 'keys[0]')
            value=$(echo $row | jq -r '.[]')
            echo "${key}=${value}" >> $GITHUB_ENV
          done
          echo "Loaded variables from $PARAMETERS_FILE."
      
      - name: Validate Variables
        run: |
          echo "team=$team"
          echo "enviroment=$enviroment"
          echo "cuenta=$cuenta"
          echo "bucketartifact=$bucketartifact"
          echo "$JUANPI"

      - name: Process Tags
        run: |
          # Convertir el JSON a pares de clave=valor escapados
          JSON=$(cat tags-dev.json)
          TAGS=$(echo "$JSON" | jq -r 'map("\(.Key)=\(.Value|gsub(" "; "_")|gsub("&"; "y"))") | join(" ")')
          echo "TAGS=${TAGS}" >> $GITHUB_ENV
          echo "Processed tags: ${TAGS}"

      - name: connect to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-session-name: awsroledeploy
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy S3 de juanpi
        id: s3
        shell: bash
        if: contains(github.event.head_commit.message, '-s3') || contains(github.event.head_commit.message, '-all')
        env:
          S3_STACK_NAME: da-juanpi-s3
        run: |
          aws cloudformation deploy --template-file template/s3.yaml \
            --region $REGION \
            --stack-name $S3_STACK_NAME \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset \
            --tags $TAGS \
            --parameter-overrides \
                pTeamName=$team \
                Stage=$enviroment \
                bucketartifact=$bucketartifact
          aws cloudformation describe-stack-events --stack-name $S3_STACK_NAME --max-items 5

      - name: Deploy S3 de lambda
        id: lambda
        shell: bash
        if: contains(github.event.head_commit.message, '-s3') || contains(github.event.head_commit.message, '-all')
        env:
          S3_STACK_NAME: da-juanpi-s3
        run: |
          aws cloudformation deploy --template-file template/s3.yaml \
            --region $REGION \
            --stack-name $S3_STACK_NAME \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset \
            --tags $TAGS \
            --parameter-overrides \
                pTeamName=$team \
                Stage=$enviroment \
                bucketartifact=$bucketartifact
          aws cloudformation describe-stack-events --stack-name $S3_STACK_NAME --max-items 5