name: Sync File to S3

on:
  push:
    branches:
      - develop # Solo se ejecutará cuando haya cambios en la rama main

permissions:
  id-token: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      AWS_BUCKET_NAME: "prueba-exampe-josemaria-git"
      REGION: "us-east-1"
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set Parametros
        run: |
          echo "$REGION"